#!/bin/bash
#
# detect-concentrator.sh — identify the attached LoRa concentrator and write the
# result to /etc/iot-hub/concentrator.env.
#
# This exists so the onboarding app can show the user their gateway EUI *before*
# any credentials exist — at that point the Basic Station container is not
# running, so its own detection is unavailable. Once provisioned, the container
# reads the EUI from the chip itself (GATEWAY_EUI_SOURCE=chip) and this file is
# informational.
#
# The *region* is deliberately not detected and never should be: Basic Station
# receives its channel plan from the LNS, so an EU868 and a US915 card produce
# identical device configuration.
#
# Safe to re-run; the env file is rewritten from scratch each time.

set -euo pipefail

ENV_FILE="${ENV_FILE:-/etc/iot-hub/concentrator.env}"
RESET_BIN="${RESET_BIN:-/usr/local/bin/concentrator-reset}"
CHIP_ID_BIN="${CHIP_ID_BIN:-/usr/local/bin/util_chip_id}"
RESET_SHIM="${RESET_SHIM:-/usr/local/bin/reset_lgw.sh}"
SPI_DEV="${SPI_DEV:-/dev/spidev0.0}"

log() { printf '%s\n' "$*" >&2; }
die() { printf 'detect-concentrator: %s\n' "$*" >&2; exit 1; }

[ -x "$CHIP_ID_BIN" ] || die "$CHIP_ID_BIN not found; run install-ubuntu.sh first"

# chip_id shells out to "./reset_lgw.sh", so it has to run from a directory that
# contains one. Give it a scratch directory rather than depending on the caller's
# working directory.
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT
if [ -x "$RESET_SHIM" ]; then
    cp "$RESET_SHIM" "$WORK_DIR/reset_lgw.sh"
else
    printf '#!/bin/sh\nexec %s "${1:-start}"\n' "$RESET_BIN" > "$WORK_DIR/reset_lgw.sh"
fi
chmod +x "$WORK_DIR/reset_lgw.sh"

# "INFO: concentrator EUI: 0x0016c001ff1e96bb" -> "0016C001FF1E96BB"
extract_eui() {
    sed -n 's/.*concentrator EUI:[[:space:]]*0x\([0-9A-Fa-f]\{16\}\).*/\1/p' \
        | head -n1 \
        | tr '[:lower:]' '[:upper:]'
}

probe() {
    # $1 = extra chip_id flags, $2 = device path
    ( cd "$WORK_DIR" && "$CHIP_ID_BIN" $1 -d "$2" 2>&1 ) | extract_eui
}

INTERFACE=""
DEVICE=""
EUI=""

if [ -e "$SPI_DEV" ]; then
    log "probing SPI on $SPI_DEV ..."
    EUI="$(probe "" "$SPI_DEV" || true)"
    if [ -n "$EUI" ]; then
        INTERFACE="SPI"
        DEVICE="$SPI_DEV"
    fi
fi

if [ -z "$INTERFACE" ]; then
    log "no concentrator on SPI; probing USB ..."
    for dev in /dev/ttyACM*; do
        [ -e "$dev" ] || continue
        EUI="$(probe "-u" "$dev" || true)"
        if [ -n "$EUI" ]; then
            INTERFACE="USB"
            DEVICE="$dev"
            break
        fi
    done
fi

[ -n "$INTERFACE" ] || die "no concentrator detected on SPI or USB — check that the card is seated in the HAT and that RESET_PIN in /etc/iot-hub/concentrator.conf matches your board"

# RAK5146 is SX1303, RAK2287 is SX1302. Both are the Semtech CORECELL design and
# are driven identically, so the model label is informational; the Basic Station
# image derives what it needs from MODEL in the compose file.
MODEL="RAK5146"
DESIGN="CORECELL"

mkdir -p "$(dirname "$ENV_FILE")"
cat > "$ENV_FILE" <<EOF
# Generated by detect-concentrator.sh — do not edit by hand.
# Re-run the script after changing the concentrator card.
#
# No region or channel plan appears here by design: the LNS supplies it.
MODEL=$MODEL
DESIGN=$DESIGN
INTERFACE=$INTERFACE
DEVICE=$DEVICE
GATEWAY_EUI=$EUI
EOF

log "detected $MODEL ($DESIGN) on $INTERFACE $DEVICE, EUI $EUI"
log "wrote $ENV_FILE"

# ---------------------------------------------------------------------------
# Render station.conf.
#
# Two things depend on this file existing:
#   1. It puts the container into STATIC mode, where credentials are read from
#      tc.uri/tc.trust/tc.crt/tc.key files — the flow Chirp issues. Without it
#      the image runs in DYNAMIC mode and refuses to start without a TC_KEY
#      token, which certificate auth does not have.
#   2. Its "routerid" must be a valid EUI. The image's own station.corecell.conf
#      ships routerid "", which Basic Station rejects as an illegal EUI and then
#      discards the entire file.
#
# Written only when missing or when the routerid does not match the card, so a
# hand-edited config survives a restart but swapping the concentrator is picked
# up automatically.
# ---------------------------------------------------------------------------

STATION_CONF="${STATION_CONF:-/etc/iot-hub/lorawan/station.conf}"
STATION_TEMPLATE="${STATION_TEMPLATE:-/etc/iot-hub/station.conf.template}"

if [ ! -f "$STATION_TEMPLATE" ]; then
    log "note: $STATION_TEMPLATE missing, leaving station.conf alone"
elif [ -f "$STATION_CONF" ] && grep -q "\"routerid\"[[:space:]]*:[[:space:]]*\"$EUI\"" "$STATION_CONF"; then
    log "station.conf already matches EUI $EUI"
else
    mkdir -p "$(dirname "$STATION_CONF")"
    sed "s/__GATEWAY_EUI__/$EUI/" "$STATION_TEMPLATE" > "$STATION_CONF.tmp"
    mv "$STATION_CONF.tmp" "$STATION_CONF"
    log "rendered $STATION_CONF with routerid $EUI"
fi
